### ISSUE TITLE
Add Org / Space ID + Space Name Spec

### ISSUE THREAD

**Issue by ehaselwanter** [mondoohq/docs#160]
#### Summarize the content issue

Can't find info on  Org / Space ID + Space Name

#### What the docs say

Did not find anything

#### What the docs SHOULD say

Org / Space ID: lowercase letters, digits or hyphens, and must start with a lowercase letter, less then 35 chars, more then 6 chars
Regex: `^[a-z]([\d-_]|[a-z]){4,33}[a-z\d]$`

Org / Space Name: name: letters, numbers, single quotes, hyphens, spaces or exclamation points, more then 4 chars
Regex: `^([a-zA-Z \-'_]|\d){2,30}$`

**Comment by misterpantz** [comment]
Thank you, @ehaselwanter! The instructions for adding new orgs/spaces were missing some of this information. We very much appreciate the feedback. The fix will be live in a few minutes!
